import { useState } from "react";
import { DivContainerModel } from "../component/container/divContainer/divContainer";
import { Design } from "../component/design";
import { TestPreview } from "./testPreview";

export const TestHome = () => {
  const [rootElement, setRootElement] = useState<DivContainerModel>({
    id: "root",
    type: "DivContainer",
    width: "900",
    height: "1240",
    border: "1px solid gray",
    padding: "16px",
    pagerWidth: 460,
    pagerHeight: 620,
    scale: 3,
    children: [
      {
        id: "b0955086-4a0a-48e9-9193-e5f5218af44f",
        type: "Label",
        position: "absolute",
        text: "销 售 单",
        display: "inline-block",
        padding: "4px",
        children: [],
        left: 303,
        top: "30",
        fontSize: "20px",
        fontWeight: "700",
        width: 252,
        height: "60",
        verticalAlign: "center",
        textAlign: "center",
      },
      {
        id: "dfb72882-a19d-4e89-9fcd-40ea184684c2",
        type: "Label",
        position: "absolute",
        text: "公司: {companyName}",
        display: "inline-block",
        padding: "8px",
        children: [],
        left: 14,
        top: 106,
        width: 436,
        height: "",
        fontSize: "13px",
        fontWeight: "600",
        verticalAlign: "center",
      },
      {
        id: "fc915750-8f71-4ad6-a795-3d447960481d",
        type: "Label",
        position: "absolute",
        text: "单号: {saleNo}",
        display: "inline-block",
        padding: "8px",
        children: [],
        left: 514,
        top: 105,
        width: "366",
        height: "",
        textAlign: "right",
        fontSize: "13px",
        fontWeight: "600",
        verticalAlign: "center",
      },
      {
        id: "f684800f-61fa-487f-9c92-57e5d01aafd3",
        type: "DivContainer",
        width: "870",
        height: 919,
        position: "absolute",
        children: [
          {
            id: "b5863a8d-873c-4bab-98df-ad5cc79806f2",
            type: "DivContainer",
            width: "",
            height: "34",
            position: "static",
            children: [
              {
                id: "61d3e08b-aa0a-411b-9413-82c2d885cab4",
                type: "Label",
                position: "absolute",
                text: "{item.productName}",
                display: "inline-block",
                padding: "2px",
                children: [],
                left: 8,
                top: "0",
                bottom: "0",
                verticalAlign: "center",
                width: "240",
                fontSize: "13px",
              },
              {
                id: "b3b7add1-ebf2-453f-ab9a-d3177cceda8e",
                type: "Label",
                position: "absolute",
                text: "{item.quantity}",
                display: "inline-block",
                padding: "2px",
                children: [],
                left: "260",
                top: "0",
                width: "80",
                height: "",
                textAlign: "center",
                bottom: "0",
                verticalAlign: "center",
                fontSize: "13px",
              },
              {
                id: "89582e94-f602-4fec-ac26-d591d67f8e08",
                type: "Label",
                position: "absolute",
                text: "{item.price}",
                display: "inline-block",
                padding: "2px",
                children: [],
                left: "344",
                top: "0",
                width: "106",
                height: "",
                textAlign: "right",
                verticalAlign: "center",
                bottom: "0",
                fontSize: "13px",
              },
              {
                id: "cc3daad2-9fba-4c3d-b12b-8a3789c3309f",
                type: "Label",
                position: "absolute",
                text: "{item.memo}",
                display: "inline-block",
                padding: "2px",
                children: [],
                left: "580",
                top: "0",
                width: "",
                height: "",
                verticalAlign: "center",
                bottom: "0",
                fontSize: "13px",
                right: "0",
              },
              {
                id: "7adece6f-fa0f-4cc2-b9d7-0869e6b2ce1b",
                type: "VerticalLine",
                position: "absolute",
                display: "block",
                height: 100,
                width: 15,
                children: [],
                left: "258",
                top: "0",
              },
              {
                id: "27f37bf9-f982-4f87-8bb3-c7e3fe855747",
                type: "VerticalLine",
                position: "absolute",
                display: "block",
                height: 100,
                width: 15,
                children: [],
                left: "342",
                top: "0",
              },
              {
                id: "b71f9f9b-0f2b-4910-bf50-e47cc7519190",
                type: "VerticalLine",
                position: "absolute",
                display: "block",
                height: 100,
                width: 15,
                children: [],
                left: "576",
                top: "0",
              },
              {
                id: "89c751cd-a38a-4585-a69a-adfa8b427b01",
                type: "VerticalLine",
                position: "absolute",
                display: "block",
                height: 100,
                width: 15,
                children: [],
                left: "452",
                top: "0",
              },
              {
                id: "2f03a921-5dc7-421c-88f4-1833fb3d3c98",
                type: "Label",
                position: "absolute",
                text: "{item.subAmount}",
                display: "inline-block",
                padding: "2px",
                children: [],
                left: "454",
                top: "0",
                bottom: "0",
                verticalAlign: "center",
                width: "120",
                textAlign: "right",
                fontSize: "13px",
              },
            ],
            left: 36,
            top: 16,
            forPath: "items",
            forItemName: "item",
            border: "",
            borderRight: "1px solid gray",
            borderBottom: "1px solid gray",
            borderLeft: "1px solid gray",
          },
        ],
        left: 12,
        top: 166,
        borderBottom: "1px solid gray",
      },
      {
        id: "9483cf5c-c98e-44ab-8218-4da6600a3179",
        type: "DivContainer",
        width: "870",
        height: "34",
        position: "absolute",
        children: [
          {
            id: "4fcbdefe-9fa5-4619-83ef-4741211fe464",
            type: "Label",
            position: "absolute",
            text: "产品名",
            display: "inline-block",
            padding: "",
            children: [],
            left: 9.5,
            top: "0",
            verticalAlign: "center",
            bottom: "0",
            fontSize: "13px",
            fontWeight: "600",
          },
          {
            id: "e02f6820-2960-4c24-ab62-9a864674b0d6",
            type: "Label",
            position: "absolute",
            text: "数量",
            display: "inline-block",
            padding: "",
            children: [],
            left: "260",
            top: "0",
            width: "80",
            height: "",
            textAlign: "center",
            bottom: "0",
            verticalAlign: "center",
            fontSize: "13px",
            fontWeight: "600",
          },
          {
            id: "c8c0360a-48db-422e-b401-c6baca4484bf",
            type: "Label",
            position: "absolute",
            text: "单价",
            display: "inline-block",
            padding: "",
            children: [],
            left: "344",
            top: "0",
            width: "106",
            height: "",
            textAlign: "right",
            bottom: "0",
            verticalAlign: "center",
            fontSize: "13px",
            fontWeight: "600",
          },
          {
            id: "a5f4ee69-7495-4327-aa4f-c31cdc29ad21",
            type: "Label",
            position: "absolute",
            text: "说明",
            display: "inline-block",
            padding: "",
            children: [],
            left: "580",
            top: "0",
            width: 102,
            height: "",
            verticalAlign: "center",
            bottom: "0",
            fontSize: "13px",
            fontWeight: "600",
          },
          {
            id: "e510fdf3-acce-4f47-b07a-a6772ca08711",
            type: "VerticalLine",
            position: "absolute",
            display: "block",
            height: 100,
            width: 15,
            children: [],
            left: "258",
            top: "0",
          },
          {
            id: "170c044b-b1a6-488b-86cb-e395db7a1460",
            type: "VerticalLine",
            position: "absolute",
            display: "block",
            height: 100,
            width: 15,
            children: [],
            left: "342",
            top: "0",
          },
          {
            id: "b0beb043-3aa6-4fcf-b3ea-11f35d975b38",
            type: "VerticalLine",
            position: "absolute",
            display: "block",
            height: 100,
            width: 15,
            children: [],
            left: "576",
            top: "0",
          },
          {
            id: "b1d53245-635c-46b8-93f7-6b3a369d2420",
            type: "Label",
            position: "absolute",
            text: "小计",
            display: "inline-block",
            padding: "2px",
            children: [],
            left: "454",
            top: "0",
            bottom: "0",
            width: "120",
            height: "",
            fontWeight: "600",
            fontSize: "13px",
            verticalAlign: "center",
            textAlign: "right",
          },
          {
            id: "851e9f47-9de5-4825-8247-81a5859c2918",
            type: "VerticalLine",
            position: "absolute",
            display: "block",
            height: "",
            width: 15,
            children: [],
            left: "452",
            top: "0",
            bottom: "0",
          },
        ],
        left: "12",
        top: "134",
        border: "1px solid gray",
      },
      {
        id: "76ea0f1e-c615-4d11-8594-00ef23040a4a",
        type: "Label",
        position: "absolute",
        text: "说明: {memo}",
        display: "inline-block",
        padding: "2px",
        children: [],
        left: 8,
        top: 1127,
        width: 875,
        height: 79,
        fontSize: "12px",
      },
      {
        id: "6313b755-15a1-4c13-a422-abbcc92e397c",
        type: "Label",
        position: "absolute",
        text: "{saleTime}",
        display: "inline-block",
        padding: "2px",
        children: [],
        left: 512,
        top: 86,
        width: 368,
        height: "",
        fontSize: "13px",
        fontWeight: "600",
        textAlign: "right",
        verticalAlign: "center",
      },
      {
        id: "4416fa8d-6198-41ad-b317-ae993f456620",
        type: "Label",
        position: "absolute",
        text: "合计: {totalAmount}",
        display: "inline-block",
        padding: "2px",
        children: [],
        left: 728.5,
        top: 1099,
        width: 154,
        height: 22,
        fontSize: "13px",
        fontWeight: "600",
        textAlign: "right",
        verticalAlign: "center",
      },
    ],
  });

  const [previewVisible, setPreviewVisible] = useState(false);
  const onLayoutChanged = (layout: DivContainerModel) => {
    setRootElement(layout);
  };

  return (
    <div
      style={{
        width: "100%",
        height: "100%",
        display: "flex",
        flexDirection: "column",
      }}
    >
      <div style={{ flex: 1, height: 0 }}>
        <Design onLayoutChanged={onLayoutChanged} layout={rootElement} />
      </div>
      <div style={{ width: "100%", textAlign: "center", padding: 20 }}>
        <button onClick={() => setPreviewVisible(true)}>Show Preview</button>
      </div>
      {previewVisible && (
        <div
          style={{
            position: "fixed",
            inset: 0,
            backgroundColor: "#fff",
            display: "flex",
            flexDirection: "column",
            overflow: "auto",
          }}
        >
          <div style={{ flex: 1 }}>
            <TestPreview layout={rootElement} />
          </div>
          <div style={{ textAlign: "center", padding: 20 }}>
            <button onClick={() => setPreviewVisible(false)}>Close</button>
          </div>
        </div>
      )}
      {/* <div>{JSON.stringify(rootElement)}</div> */}
    </div>
  );
};
